#!/bin/sh

# create the mesh
foamCleanPolyMesh
blockMesh

# create the intial time folder
cp -r 0_org 0

# create C files for post-processing
postProcess -func writeCellCentres -constant

# Decompose the case in order to run in parallel (on 16 cores)
decomposePar -force

# Run sedFoam in parallel
mpirun -np 15 sedFoam_rbgh -parallel #> log&
