FROM quay.io/biocontainers/agat:1.0.0--pl5321hdfd78af_0

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="AGAT" \ 
    base_image="quay.io/biocontainers/agat:1.0.0--pl5321hdfd78af_0" \ 
    about.summary="Another Gtf/Gff Analysis Toolkit." \ 
    about.home="https://github.com/NBISweden/AGAT" \ 
    software.version="1.2.0"
    