FROM quay.io/biocontainers/bwa:0.7.17--h5bf99c6_8

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="BWA" \ 
    base_image="quay.io/biocontainers/bwa:0.7.17--h5bf99c6_8" \ 
    container="BWA" \ 
    about.summary="Burrow-Wheeler Aligner for short-read alignment (see minimap2 for long-read alignment)" \ 
    about.home="https://github.com/lh3/bwa" \ 
    software.version="0.7.17"

