FROM quay.io/qiime2/amplicon:2024.2

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Qiime2" \ 
    base_image="quay.io/qiime2/amplicon:2024.2" \ 
    container="Qiime2" \ 
    about.summary="QIIME 2 is a powerful, extensible, and decentralized microbiome analysis package with a focus on data and analysis transparency. QIIME 2 enables researchers to start an analysis with raw DNA sequence data and finish with publication-quality figures and statistical results." \ 
    about.home="https://github.com/qiime2/qiime2" \ 
    software.version="2024.2"

