FROM teambraker/braker3:v3.0.7.4

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="BRAKER3" \ 
    base_image="teambraker/braker3:v3.0.7.4" \ 
    about.summary="BRAKER is a pipeline for fully automated prediction of protein coding gene structures with GeneMark-ES/ET/EP/ETP and AUGUSTUS in novel eukaryotic genomes." \ 
    about.home="https://github.com/Gaius-Augustus/BRAKER" \ 
    software.version="3.0.8"
    