FROM us.gcr.io/broad-dsde-methods/cellbender:0.3.0

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="CellBender" \ 
    base_image="us.gcr.io/broad-dsde-methods/cellbender:0.3.0" \ 
    container="CellBender" \ 
    about.summary="CellBender is a software package for eliminating technical artifacts from high-throughput single-cell RNA sequencing (scRNA-seq) data." \ 
    about.home="https://github.com/broadinstitute/CellBender" \ 
    software.version="0.3.0"

