FROM quay.io/biocontainers/maker:3.01.03--pl5262h8f1cd36_2

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="MAKER" \ 
    base_image="quay.io/biocontainers/maker:3.01.03--pl5262h8f1cd36_2" \ 
    container="MAKER" \ 
    about.summary="MAKER is a portable and easily configurable genome annotation pipeline." \ 
    about.home="https://github.com/Yandell-Lab/maker" \ 
    software.version="3.01.03"

