FROM trinityrnaseq/trinotate:4.0.2

MAINTAINER Jason Li <jasonli3@lsu.edu>

LABEL    software="Trinotate" \ 
    base_image="trinityrnaseq/trinotate:4.0.2" \ 
    container="Trinotate" \ 
    about.summary="Trinotate is a comprehensive annotation suite designed for automatic functional annotation of transcriptomes, particularly de novo assembled transcriptomes, from model or non-model organisms." \ 
    about.home="https://github.com/Trinotate/Trinotate" \ 
    software.version="4.0.2"

ENV PATH="$PATH:/usr/local/src/Trinotate"